---
- name: Jenkins + Maven install 
  hosts: linux3 
  become: yes 

  tasks:

  - name: Remove previus version Java 
    yum: 
      name: 'java-1.7*' 
      state: absent

  - name: Install new version Java 
    yum: 
      name: 'java-1.8*' 
      state: latest

  - name: Maven download 
    get_url:
      url: https://mirror.datacenter.by/pub/apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt

  - name: Extract Maven
    unarchive: 
      src: /opt/apache-maven-3.6.3-bin.tar.gz
      dest: /opt
      remote_src: yes
  
  - name: Download Jenkins
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  
 # - name: Add key
 #   shell: 
 #     cmd: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  
  - name: Add key
    rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      state: present 

  - name: Udate Repo
    yum: 
      name: '*'
      state: latest
      update_cache: yes 

  - name: Install Jenkins  
    yum: 
      name: jenkins
      state: latest
  
  - name: Start service Jenkins 
    service: 
      name: jenkins
      state: started
      enabled: yes  
  

  - name: Copy secret code file from jenkins serv 
    fetch:
      src: /var/lib/jenkins/secrets/initialAdminPassword
      dest: ./
      flat: yes

  environment: 
    PATH: /opt/apache-maven-3.6.3/bin:{{ ansible_env.PATH }}:{{ ansible_env_JAVA_HOME }}
