---
- name: Remove Apache WebServer from servers 
  hosts: all
  become: yes 


  tasks: 
  
  - block: #Remove from RadHat

      - name:  Remove from RadHat
        yum: name={{ item }} state=absent
        loop: 
          - httpd
          - tree

    when: ansible_os_family=="RedHat"
    
  - block:  #Remove from Debian
       
      - name: Remove from Debian
        apt: name={{ item }} state=absent
        loop:
          - apache2
          - tree 


    when: ansible_os_family=="Debian"     

